app:
  name: CurrencyExchangeApp
  port: :3000

#database:
#  host: localhost
#  port: :3306
#  user: root
#  password: Love880601.
#  name: currency_exchange_db
database:
  dsn: "root:Love880601.@tcp(127.0.0.1:3306)/currency_exchange_db?charset=utf8mb4&parseTime=True&loc=Local"
  MaxIdleConns: 11
  MaxOpenConns: 100
redis:
  addr: localhost:6379
  DB: 0
  Password: ""